"""Increase password length

Revision ID: 387d4d04100a
Revises: 6fd7505ff749
Create Date: 2025-11-05 19:26:29.946103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387d4d04100a'
down_revision = '6fd7505ff749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
