"""Add payment_method to Transaction

Revision ID: 952fcb267cd0
Revises: cdbe507f5086
Create Date: 2025-11-11 13:44:00.651862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952fcb267cd0'
down_revision = 'cdbe507f5086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
